### ISSUE TITLE
Transfer this repo to the humanmade organisation

### ISSUE THREAD

**Issue by johnbillion** [humanmade/network-media-library#33]
We've decided to move this into the humanmade organisation as it's something that the HM team are interested in maintaining.

TODO:

* [x] Transfer ownership from https://github.com/johnbillion/network-media-library/settings
* [x] Change references in the code from `johnbillion` to `humanmade`
* [x] Change the Composer package name (need to look into how to do this without breaking anything)

**Comment by paulgibbs** [comment]
I'm not sure there's a good way to change the Composer package name without breaking everything, but you can mark the original package as "abandoned" on Packagist, and re-submit the new package with the new name. I would also "archive" the repo on Github for good measure.

When an abandoned package is fetched with Composer, there is a notification to tell the user to switch to the new package instead. Maybe this'll be good enough?
]
<img width="637" src="https://user-images.githubusercontent.com/1275914/47657302-b2681180-db88-11e8-9b5a-0221f07e468f.png">

**Comment by johnbillion** [comment]
💥
