### ISSUE TITLE
Share media across sites in part of multisite network?

### ISSUE THREAD

**Issue by jockebq** [humanmade/network-media-library#36]
Hi,

I use a plugin called WP Ultimo, which let's me create a network of multisites. This means that a user can register and setup one or several sites. One user can be the owner of more than one site. And I am wondering if it is possible to implement this plugin to share the media between the sites that have the same owner in the network?

Right now it is set to a specific site ID, and shared across all sites. But if it was set to the primary site of each created site in the network and shared between the sites with the same admin.

Am I way out of it with this idea, or is it something that is possible to do with a plugin like this with some modification?

Thank you for your work!

**Comment by johnbillion** [comment]
This probably is very possible, but I don't have any time to look at it at the moment, and probably won't do for a few months. Ideally the `SITE_ID` constant wouldn't be a constant, and its value could be set at runtime.

**Comment by jockebq** [comment]
@johnbillion Fantastic! I wish I could be of any help with making this happen, but I am not that great with code.

**Comment by jockebq** [comment]
@johnbillion Just thought about this a bit more, setting the SITE_ID to the primary site ID would only share the media from the primary site to all the others.
Would it be possible to share all the media from all the sites the user is admin for?
Basically if one user is the admin of 5 sites, uploading a file to site number 4 would be accessible from site 1,2,3,4,5 and same thing if a file is uploaded to any of the other sites.
Is this something that would be possible to do?

**Comment by johnbillion** [comment]
That could well be possible yes, but it's well outside the intention of this plugin.

**Comment by johnbillion** [comment]
It's just occurred to me that this is completely possible using the `network-media-library/site_id` filter. You just need to implement your own custom logic that returns the correct site ID depending on your requirements (doing that is beyond the scope of the NML plugin).

**Comment by jockebq** [comment]
I understand this is not what this plugin is trying to do. But I really think this serves a purpose. Sadly I don't know enough to use the information you gave me. But it sounds like it shouldn't be to much work? Is there anyone who has time to look at this?

**Comment by jockebq** [comment]
Do you think there is any chance you can help me out with this? It seems like you have the idea on how to do it. Can I support you somehow (Paypal) to help me with this?

Thank you!

**Comment by nciske** [comment]
@jockebq Adding a filter is something anyone with PHP chops can do. My agency could likely help you with this. Let us know if you’re interested in pursuing that here: https://luminfire.com/contact-us/project-request-form/
