### ISSUE TITLE
Media uploads to central library only work if upload from central site?

### ISSUE THREAD

**Issue by jmyt8** [humanmade/network-media-library#37]
When uploading from other sites, the uploads appear to be stored per site. Only uploads from the central site are stored in the central media library. Is the correct? or is the something wrong with my setting?

**Comment by johnbillion** [comment]
Uploads should be stored on the central media site regardless of which site you upload them from.

Do you have any other plugins on your site which might alter the way that media works on your site?

Anything unusual about your installation?

**Comment by jmyt8** [comment]
It's a new installation, haven't changed much. Only other plugin is SMTP, which has been disabled.

I think this is the problem:
The package I installed from 
> composer require humanmade/network-media-library

has a "network-media-library" folder, but inside it is multisite-global- media.php and its asssets

**Comment by johnbillion** [comment]
Not sure what's going on there. I'd try deleting the plugin and pulling it in again.
