### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Xarcell** [humanmade/network-media-library#39]
So on all except the main one, it throws a fatal error on the sites dashboard, but frontend of the sites load just fine.

`Fatal error: Uncaught TypeError: Argument 2 passed to Network_Media_Library\allow_media_library_access() must be of the type string, null given, called in /home/swagger7/public_html/wp-includes/class-wp-hook.php on line 286 and defined in /home/swagger7/public_html/wp-content/plugins/network-media-library-master/network-media-library.php:381 Stack trace: #0 /home/swagger7/public_html/wp-includes/class-wp-hook.php(286): Network_Media_Library\allow_media_library_access(Array, NULL, 1, Array) #1 /home/swagger7/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /home/swagger7/public_html/wp-includes/capabilities.php(589): apply_filters('map_meta_cap', Array, NULL, 1, Array) #3 /home/swagger7/public_html/wp-includes/class-wp-user.php(722): map_meta_cap(NULL, 1) #4 /home/swagger7/public_html/wp-includes/capabilities.php(623): WP_User->has_cap(NULL) #5 /home/swagger7/public_html/wp-admin/includes/plugin.php(1101): current_user_can(NULL) #6 /home/swagger7/public_html/wp-content/plugins/wp-power-stats in /home/swagger7/public_html/wp-content/plugins/network-media-library-master/network-media-library.php on line 381`

**Comment by johnbillion** [comment]
It looks like this might be caused by the `wp-power-stats` plugin. It could be calling or filtering the capabilities system incorrectly. Can you try deactivating it to see if the problem goes away?

**Comment by Xarcell** [comment]
Yes, it was caused by the power stats plugin. Works great without it. Any chance these two plugins can be made compatible?

**Comment by johnbillion** [comment]
Looking at the stack trace you provided, something in wp-power-stats is calling `current_user_can()` with `null` as its first parameter. You might want to let the plugin author know. Don't forget to check to see if you're using the latest version first.

**Comment by Xarcell** [comment]
Thanks for your help.
