### ISSUE TITLE
  Notice: Trying to get property 'post_type' of non-object in /var/www/html/wp-content/plugins/network-media-library-master/network-media-library.php on line 355

### ISSUE THREAD

**Issue by stevebab** [humanmade/network-media-library#43]
Just installed 1.4.1.

Getting this error.

**Comment by stevebab** [comment]
Reinstalled. Working ok now.

**Comment by johnbillion** [comment]
Thanks for the update! Let us know if you see the error again.

**Comment by semammerlaan** [comment]
Hi John,

Installed latest version and getting this error on main site id (1):

Notice: Trying to get property 'post_type' of non-object in /home/avocadotester/domains/avocado-test.nl/public_html/jsw/wp-content/plugins/network-media-library-master/network-media-library.php on line 359

**Comment by Pierronimo** [comment]
Hi John,

I got the same error message :
Notice: Trying to get property 'post_type' of non-object in /Users/pierreferron/Sites/diving-experience-test.com/wp-content/plugins/network-media-library.php on line 359

In my case, I have the polylang plugin activated, when I see the list in one language, no problem, but if I select "Show all languages" then the error messages appears.

I tried to reinstall but have the same result

![Capture d’écran 2020-05-26 à 14 18 15](https://user-images.githubusercontent.com/65741750/82941374-dbff3f80-9f5b-11ea-8027-ec783d9c5253.jpg)
![Capture d’écran 2020-05-26 à 14 18 23](https://user-images.githubusercontent.com/65741750/82941376-dd306c80-9f5b-11ea-98a7-0902544bb015.jpg)
