### ISSUE TITLE
Warning: implode(): Invalid arguments passed in G:\...\wp-admin\edit-form-blocks.php on line 251

### ISSUE THREAD

**Issue by razvancuceu** [humanmade/network-media-library#46]
I have only this plugin installed on a multisite setup and get this error
`Warning: implode(): Invalid arguments passed in G:\...\wp-admin\edit-form-blocks.php on line 251`

**Comment by johnbillion** [comment]
Which version of WordPress are you using?

Does the error appear when a default theme such as Twenty Nineteen is in use?

Anything unusual about your network setup?

Can you get a full stack trace for that error?
