### ISSUE TITLE
short delay when adding images?

### ISSUE THREAD

**Issue by fine-G** [humanmade/network-media-library#54]
is there a short delay on child sites, when an asset is added? 

We make an impure plugin. When we add an image on site of the library it is immediately there.
On the other sites the function can't find the image. after a very short moment it is there…

**Comment by johnbillion** [comment]
Nope there's no delay. You may have some caching in place which is causing this delay, although caching of calls to `WP_Query` isn't very common. I would try deactivating your other plugins to see if you can find the problem.
