### ISSUE TITLE
Translated alt text to images

### ISSUE THREAD

**Issue by mikepeperoni** [humanmade/network-media-library#56]
Hello and congrats for this plugin.
It would be most useful if you could add an option to translate the alt text and title of the images, to the site's preferred language. You see, most of the people who create a WP network is because they want to have a multilingual install. Like myself!
Anyways, thank you for creating this -we do hope that you 'll keep developing it, for the sake of us all...
Best regards,
Mike

**Comment by marcin-biegun** [comment]
that would be really helpful - just planning switch from wpml to multisite but missing the possibility to translate alt...

**Comment by johnbillion** [comment]
Thanks for the suggestions folks, but Network Media Library isn't specifically for creating multilingual sites and I think such functionality falls outside of the intention of this plugin.

If you're using Multisite to create a multilingual network then your best bet is to use MultilingualPress which handles all of this for you.
