### ISSUE TITLE
Avoid need for users to be a member of the Media site

### ISSUE THREAD

**Issue by johnbillion** [humanmade/network-media-library#6]
Currently, users need to be manually added to the central media site with at least the `upload_files` capability, and the ability to edit attachments. This should be transparently handled by the plugin, so if the user can manage media on the site that they're on then they can also manage media on the central media site.

**Comment by jockebq** [comment]
Thank you for the work on this plugin! At first I thought it solved all the problems I've had with Multisite Global Media. Mainly what you are talking about here. I am using a plugin called WP Ultimo which let's me create a Wordpress Network with sites. And I want all the users of these sites to be able to access some "sample" media. But it would be amazing if it was possible to do this without the need to give them permissions to the site which stores the media. I think this is a security thing, and there is no automatic way when users creates a new site to get them to join the network media site?

**Comment by johnbillion** [comment]
It should be possible to do this "behind the scenes" by utilising the user capability mapping filters, I just haven't had a chance to look into it yet.

**Comment by johnbillion** [comment]
Re-opening this as it's partially fixed in 1.2.0.

In order for a user to edit an attachment's details, such as the title and caption, the user still needs to be added to the media site with the ability to edit attachments.

**Comment by jockebq** [comment]
> 
> 
> Re-opening this as it's partially fixed in 1.2.0.
> 
> In order for a user to edit an attachment's details, such as the title and caption, the user still needs to be added to the media site with the ability to edit attachments.

I just tried it out! And I can access the images on the specified site easily! I just have two questions.
1. In the file settings I specified site ID 10, and when I logged in to another site (called ID 47) I could see the images from site ID 10. But if I uploaded an image on site ID 47 it will appear on site ID 10 media library too. Would it be possible to allow only users to upload to their own site, but still access all the files on site ID 10?
2. Is it possible to be used for more than images? Right now I can only see images, not videos.

**Comment by johnbillion** [comment]
> 1. Would it be possible to allow only users to upload to their own site, but still access all the files on site ID 10?

Nope, this plugin specifically provides only a central media library. You can try the [Multisite Global Media plugin](https://github.com/bueltge/multisite-global-media) which does allow this.

> 2. Is it possible to be used for more than images? Right now I can only see images, not videos.

It should work for any media, but it's only really been extensively tested with images. Can you open a separate issue with some details? Thanks.

**Comment by jockebq** [comment]
> Nope, this plugin specifically provides only a central media library. You can try the [Multisite Global Media plugin](https://github.com/bueltge/multisite-global-media) which does allow this.
Oh, sorry about that. I originally came from Multisite Global Media, that's how I found your version. But sadly Multisite Global Media requires the user to have access to the "main" site for it to work. Would your solution to this be possible to implement in Multisite Global Media too?

> It should work for any media, but it's only really been extensively tested with images. Can you open a separate issue with some details? Thanks.
Yes, I will report back later.
