### ISSUE TITLE
Advanced Custom Fields image field always returns image ID, not image array or URL

### ISSUE THREAD

**Issue by first-wgrt** [humanmade/network-media-library#62]
When creating an image field in ACF, one can adjust the field's return format. Three options are available: Image array (default), Image URL and Image ID:

![image](https://user-images.githubusercontent.com/55440658/65036564-ff450a00-d94b-11e9-84df-496d4fa8239f.png)

When using Network Media Library, `get_field()` calls on image fields always return the image's ID, no matter the setting mentioned above. 

I'm using Network Media Library 1.5.0 and ACF PRO 5.8.4 on Wordpress 5.2.3.

**Comment by thomasdebruin** [comment]
For me it's fixed by this pull request https://github.com/humanmade/network-media-library/pull/52/commits/79843fa7679eca14512c72453a37f818ab369d83#diff-873cde10e3373d7947baeca176bfee7e

**Comment by first-wgrt** [comment]
That fixes it for me too, kudos @thomasdebruin!
