### ISSUE TITLE
Image sharing on existing Multi-site 

### ISSUE THREAD

**Issue by dennislam08** [humanmade/network-media-library#71]
It is a problem when I install this plugin on the existing multi-site, I can't get the image on the subsites.

I suggest we can check the image before it returns the result on wp_get_attachment_image_src filter function. If the image array is empty after switched to the media site, we can get the image from the current blog.

![Screenshot 2020-03-16 at 1 11 15 PM](https://user-images.githubusercontent.com/19659669/76724981-ba2d5380-6787-11ea-9206-bae9829762d2.png)

**Comment by johnbillion** [comment]
Thanks for the report. This is not a use case that this plugin will support because it greatly increases the complexity. I recommend checking out [the alternatives](https://github.com/humanmade/network-media-library#alternatives).
