### ISSUE TITLE
Notice: Trying to get property 'post_type' of non-object in /var/www/html/wp-content/plugins/network-media-library-master/network-media-library.php on line 355

### ISSUE THREAD

**Issue by Leobar00** [humanmade/network-media-library#86]
I installed the plugin to share the gallery from the main site to all the sites in the network.

Setting the variable site_id to 1, the secondary site with id 2 works correctly, while the dashboard of the main site displays the following error:
Notice: Trying to get property 'post_type' of non-object in /var/www/html/wp-content/plugins/network-media-library-master/network-media-library.php on line 355

I consulted the issues opened by other users, but no solution worked for me.

**Comment by rgarciacostex** [comment]
Although I'm commenting 30 days after you, I'm seeing the same issue.  We have a main site with subfolder sites for different languages. 
Same exact error.

**Comment by davidholtz** [comment]
Also seeing this. No resolution yet.

**Comment by pederan** [comment]
Same issue here. needed to maka a clone/local copy in the project and change this part in the function, https://github.com/humanmade/network-media-library/blob/master/network-media-library.php#L357-L365
with the code below. Then it works :) 
```
if ( 'edit_post' === $cap ) {
	$content = get_post( $args[0] );
	// Start: Fix, since $content can be null.
	if( ! $content instanceof \WP_Post ) {
		return $caps;
	}
	// End: Fix, since $content can be null.
	if ( 'attachment' !== $content->post_type ) {
		return $caps;
	}

	// Substitute edit_post because the attachment exists only on the network media site.
	$cap = get_post_type_object( $content->post_type )->cap->create_posts;
}
```
